# -*- coding: utf-8 -*-
"""experiment1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YiXSooRHpbEqYp6KSCLttfxl4p5Blq4
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

INPUT_IMAGE = "/content/Screenshot 2026-07-23 113126.png"

img = cv2.imread(INPUT_IMAGE)

if img is None:
    raise FileNotFoundError(
        "Image load nahi hui. Please check that the image is uploaded."
    )

print("✅ Image successfully loaded!")
print("Image dimensions:", img.shape)

import cv2
import numpy as np
import matplotlib.pyplot as plt

height, width = img.shape[:2]
channels = img.shape[2]

print("\n========== IMAGE PROPERTIES ==========")
print("Width:", width)
print("Height:", height)
print("Dimensions:", img.shape)
print("Number of Channels:", channels)
print("Data Type:", img.dtype)
print("=======================================")

import cv2
import numpy as np
import matplotlib.pyplot as plt

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,5))
plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

cv2.imwrite("/content/output.jpg", img)
cv2.imwrite("/content/output.png", img)

print("\n✅ Image saved as output.jpg")
print("✅ Image saved as output.png")

import cv2
import numpy as np
import matplotlib.pyplot as plt

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

print("\n✅ RGB/BGR → Grayscale")
print("✅ BGR → HSV")
print("✅ BGR → LAB")

import cv2
import numpy as np
import matplotlib.pyplot as plt

resized = cv2.resize(img, (300, 300))

print("\n✅ Image resized to 300 x 300")

import cv2
import numpy as np
import matplotlib.pyplot as plt

rotated = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
print("✅ Image rotated 90 degrees clockwise")

import cv2
import numpy as np
import matplotlib.pyplot as plt

horizontal_flip = cv2.flip(img, 1)
vertical_flip = cv2.flip(img, 0)

print("✅ Horizontal flip completed")
print("✅ Vertical flip completed")

import cv2
import numpy as np
import matplotlib.pyplot as plt

negative = 255 - img

print("✅ Negative image created")

import cv2
import numpy as np
import matplotlib.pyplot as plt

roi_height = height // 2
roi_width = width // 2

start_y = height // 4
start_x = width // 4

roi = img[
    start_y:start_y + roi_height,
    start_x:start_x + roi_width
]

print("✅ ROI created")

import cv2
import numpy as np
import matplotlib.pyplot as plt

cv2.imwrite("/content/grayscale.jpg", gray)
cv2.imwrite("/content/resized.jpg", resized)
cv2.imwrite("/content/rotated.jpg", rotated)
cv2.imwrite("/content/horizontal_flip.jpg", horizontal_flip)
cv2.imwrite("/content/vertical_flip.jpg", vertical_flip)
cv2.imwrite("/content/negative.jpg", negative)
cv2.imwrite("/content/roi.jpg", roi)

print("\n✅ All processed images saved successfully!")

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

hsv_rgb = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)

plt.figure(figsize=(6, 5))
plt.imshow(hsv_rgb)
plt.title("HSV Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

lab_rgb = cv2.cvtColor(lab, cv2.COLOR_LAB2RGB)

plt.figure(figsize=(6, 5))
plt.imshow(lab_rgb)
plt.title("LAB Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(cv2.cvtColor(resized, cv2.COLOR_BGR2RGB))
plt.title("Resized Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(cv2.cvtColor(rotated, cv2.COLOR_BGR2RGB))
plt.title("Rotated Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(cv2.cvtColor(horizontal_flip, cv2.COLOR_BGR2RGB))
plt.title("Horizontal Flip")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(cv2.cvtColor(vertical_flip, cv2.COLOR_BGR2RGB))
plt.title("Vertical Flip")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(cv2.cvtColor(negative, cv2.COLOR_BGR2RGB))
plt.title("Negative / Complement Image")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
plt.title("Region of Interest (ROI)")
plt.axis("off")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 3, figsize=(12, 8))

axes[0, 0].imshow(img_rgb)
axes[0, 0].set_title("Original")

axes[0, 1].imshow(gray, cmap="gray")
axes[0, 1].set_title("Grayscale")

axes[0, 2].imshow(hsv_rgb)
axes[0, 2].set_title("HSV")

axes[1, 0].imshow(lab_rgb)
axes[1, 0].set_title("LAB")

axes[1, 1].imshow(cv2.cvtColor(negative, cv2.COLOR_BGR2RGB))
axes[1, 1].set_title("Negative")

axes[1, 2].imshow(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
axes[1, 2].set_title("ROI")

for ax in axes.ravel():
    ax.axis("off")

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

print("\n========== OUTPUT FILES ==========")

files = [
    "output.jpg",
    "output.png",
    "grayscale.jpg",
    "resized.jpg",
    "rotated.jpg",
    "horizontal_flip.jpg",
    "vertical_flip.jpg",
    "negative.jpg",
    "roi.jpg"
]

for file in files:
    if os.path.exists("/content/" + file):
        print("✅", file)

print("\n🎉 EXPERIMENT 1 COMPLETED SUCCESSFULLY!")